- name: Install dunst
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - dunst

- name: Ensure dunst config directory exists
  file:
    path: "/home/{{ system_user_name }}/.config/dunst"
    state: directory

- name: Ensure configs are in place
  ansible.builtin.copy:
    src: "files/wm/dunst/"
    dest: "/home/{{ system_user_name }}/.config/dunst/"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'

