- name: Install dunst
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - dunst

- name: Ensure dunst config directory exists
  file:
    path: "/home/{{ item }}/.config/dunst"
    state: directory
  loop:
    - diffy

- name: Copy dunst config
  template:
    src: files/wm/dunst/dunstrc.j2
    dest: "/home/{{ item }}/.config/dunst/dunstrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop:
    - diffy
