---
- name: Install i3 tiling window manager
  pacman:
    name:
      - i3-gaps

- name: Ensure i3 config directory exists
  file:
    path: "/home/{{ item }}/.config/i3"
    state: directory
  loop:
    - diffy

- name: Copy i3 config
  template:
    src: files/wm/i3/config.j2
    dest: "/home/{{ item }}/.config/i3/config"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop:
    - diffy