---
- name: Install i3 tiling window manager
  pacman:
    name:
      - i3-gaps

- name: Ensure i3 config directory exists
  file:
    path: "/home/{{ item }}/.i3"
    state: directory
  loop:
    - diffy
    - panic

- name: Copy i3 config
  template:
    src: files/wm/i3/config.j2
    dest: "/home/{{ item }}/.i3/config"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop:
    - diffy
    - panic

- name: Install polybar
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - polybar

- name: Ensure polybar config directory exists
  file:
    path: "/home/{{ item }}/.config/polybar"
    state: directory
  loop:
    - diffy
    - panic

- name: Copy polybar config
  template:
    src: files/wm/polybar/config.j2
    dest: "/home/{{ item }}/.config/polybar/config"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop:
    - diffy
    - panic


## https://github.com/polybar/polybar/wiki
## start with polybar example
## 1. Configure bar
## 2. Start on i3