---
- name: Install i3 tiling window manager
  pacman:
    name:
      - i3-gaps
      - brillo

- name: Ensure i3 config directory exists
  file:
    path: "/home/{{ system_user_name }}/.config/i3"
    state: directory

- name: Ensure configs are in place
  ansible.builtin.copy:
    src: "files/wm/i3/config"
    dest: "/home/{{ system_user_name }}/.config/i3/config"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'

- name: Ensure scripts are in place and executable
  ansible.builtin.copy:
    src: "files/wm/i3/scripts/"
    dest: "/home/{{ system_user_name }}/.config/i3/scripts/"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0755'
