- name: Install picom compositor
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - picom

- name: Ensure picom config directory exists
  file:
    path: "/home/{{ system_user_name }}/.config/picom"
    state: directory

- name: Copy picom config
  template:
    src: files/wm/picom/picom.conf.j2
    dest: "/home/{{ system_user_name }}/.config/picom/picom.conf"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'
