- name: Install polybar
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - polybar

- name: Ensure polybar config directory exists
  file:
    path: "/home/{{ system_user_name }}/.config/polybar"
    state: directory

- name: Copy polybar config
  template:
    src: files/wm/polybar/config.j2
    dest: "/home/{{ system_user_name }}/.config/polybar/config"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'

- name: Copy polybar config lanuncher
  template:
    src: files/wm/polybar/launch.sh.j2
    dest: "/home/{{ system_user_name }}/.config/polybar/launch.sh"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0775'
