---
- name: Install rofi
  pacman:
    name:
      - rofi

- name: Ensure rofi config directory exists
  file:
    path: "/home/{{ system_user_name }}/.config/rofi"
    state: directory

- name: Ensure configs are in place
  ansible.builtin.copy:
    src: "files/wm/rofi/"
    dest: "/home/{{ system_user_name }}/.config/rofi/"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'

