---
- name: Ensure zsh and its plugins are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - zsh
    - zsh-completions
  
- name: Copy .zshrc config
  template:
    src: files/shells/zsh/.zshrc.j2
    dest: "/home/{{ system_user_name }}/.zshrc"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'
