---
  - name: "Arch Boot - Hosts file setup"
    hosts: localhost
    connection: local 
    gather_facts: false
    become: yes
    vars_files:
      - vars/hosts.yml
    tasks:
      - name: Update the /etc/hosts file with local groups
        blockinfile:
          path: "/etc/hosts"
          backup: yes
          block: |
            {{ item.ip }} {{ item.hostnames | join(' ') }}
          marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.name }}"
        with_items: "{{ hosts.set }}"

      - name: Remove group of hosts from /etc/hosts file
        blockinfile:
          path: "/etc/hosts"
          backup: yes
          state: absent
          marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item }}"
        with_items: "{{ hosts.unset }}"