---
- name: Install Alacritty terminal emulator
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - alacritty

- name: Ensure alacritty config directory exists
  file:
    path: "/home/{{ system_user_name }}/.config/alacritty"
    state: directory

- name: Ensure configs are in place
  copy:
    src: "files/terminals/alacritty/"
    dest: "/home/{{ system_user_name }}/.config/alacritty/"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'