---
- name: Ensure starship prompt is installed
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - starship

- name: Ensure configs are in place
  copy:
    src: "files/terminals/starship/"
    dest: "/home/{{ system_user_name }}/.config/starship/"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'