---
- name: Ensure command files are copied into /bin
  ansible.builtin.copy:
    src: "files/bin/"
    dest: "/bin"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0775'