---
- name: Ensure ssh key files are in place for users
  ansible.builtin.copy:
    src: "files/certs/.ssh/"
    dest: "/home/{{ system_user_name }}/.ssh"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '600'