---
- name: Ensure all git packages are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - git
    - gitkraken
    - gitui
    
- name: Ensure gitconfig is copied to each user
  template:
    src: "files/git/.gitconfig.j2"
    dest: "/home/{{ system_user_name }}/.gitconfig"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'