---
## Group and user `panic` is for work
## Group and user `diffy` is for personal projects, learning etc..
## Group `common` is to share files between my users

## Should skip if group exists
- name: Ensure group "panic" exists with correct gid
  group:
    name: panic
    state: present
    gid: 1001

- name: Add the user 'diffy' with a zsh shell, appending the group 'diffy' to the user's groups
  user:
    name: diffy
    password: "{{diffy_password}}"
    uid: 1000
    create_home: yes
    shell: /bin/zsh
    groups: diffy, wheel
    append: yes

- name: Add the user 'panic' with a zsh shell, appending the group 'panic' to the user's groups
  user:
    name: panic
    password: "{{panic_password}}"
    uid: 1001
    create_home: yes
    shell: /bin/zsh
    groups: panic, wheel
    append: yes

# Common group is for this ansible playbook, so diffy and panic can both run it.
- name: Ensure group "common" exists with correct gid
  group:
    name: common
    state: present
    gid: 2000

- name: adding existing user '{{ item }}' to group common
  user:
    name: "{{ item }}"
    groups: common
    append: yes
  loop:
    - diffy
    - panic

- name: Ensure common folder exists
  file:
    path: "/home/common/"
    state: directory
    owner: diffy
    group: common
    mode: '770'

- name: Ensure Documents folder exists
  file:
    path: "/home/common/Documents"
    state: directory
    owner: diffy
    group: common
    mode: '770'

- name: Ensure Videos folder exists
  file:
    path: "/home/common/Videos"
    state: directory
    owner: diffy
    group: common
    mode: '770'
