---
## Group `common` is to share files between my users
- name: Add the user 'diffy' with a zsh shell, appending the group 'diffy' to the user's groups
  user:
    name: diffy
    password: "{{diffy_password}}"
    uid: 1000
    create_home: yes
    shell: /bin/zsh
    groups: diffy, wheel, uucp
    append: yes

- name: adding existing user '{{ item }}' to group common
  user:
    name: "{{ item }}"
    groups: common
    append: yes
  loop:
    - diffy

- name: Ensure common folder exists
  file:
    path: "/home/common/"
    state: directory
    owner: diffy
    group: common
    mode: '770'

- name: Ensure Important folder exists
  file:
    path: "/home/common/Important"
    state: directory
    owner: diffy
    group: common
    mode: '770'
