---
- name: Ensure neo vim and its plugins are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - neovim
    - nvim-packer-git

- name: Copy nvim config
  copy:
    src: files/nvim/
    dest: "/home/{{ item }}/.config/nvim"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop:
    - diffy
