---
- name: Install docker and docker-compose
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - docker
    - docker-compose
    - ctop

- name: Enable and make sure running the service docker
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: adding existing user '{{ system_user_name }}' to group docker
  user:
    name: "{{ system_user_name }}"
    groups: docker
    append: yes

- name: Log into docker registry
  docker_login:
    config_path: "/home/{{ system_user_name }}/.docker/config.json"
    registry: "{{ item.registry }}"
    username: "{{ item.user_name }}"
    password: "{{ item.user_token }}"
  with_items: "{{ docker_logins }}"