---
- name: Install docker and docker-compose
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - docker
    - docker-compose
    - ctop

- name: Enable and make sure running the service docker
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: adding existing user '{{ item }}' to group docker
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - diffy
