---
- name: Ensure packages for javascript development are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - nodejs
    - yarn
    - webstorm
  
- name: Ensure typescript is installed
  npm:
    name: typescript
    global: yes