---
- name: Ensure packages for javascript development are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - nodejs
    - yarn
    - webstorm
  
- name: Ensure typescript is installed
  npm:
    name: typescript
    global: yes
  
- name: Ensure jest is installed
  npm:
    name: jest
    global: yes
  
- name: Ensure sonar-scanner is installed
  npm:
    name: sonar-scanner
    global: yes