---
- name: Ensure docker development is ready
  include_tasks: docker.yml

- name: Ensure python development is ready
  include_tasks: python.yml

- name: Ensure arduino development is ready
  include_tasks: arduino.yml
  when: false

- name: Ensure ansible development is ready
  include_tasks: ansible.yml

- name: Ensure php development is ready
  include_tasks: php.yml

- name: Ensure dotnet development is ready
  include_tasks: dotnet.yml
  when: false

- name: Ensure javascript development is ready
  include_tasks: javascript.yml

- name: Ensure vscode development is ready
  include_tasks: vscode.yml

- name: Ensure rust development is ready
  include_tasks: rust.yml

- name: Ensure rust development is ready
  include_tasks: golang.yml

- name: Ensure utils for development is ready
  include_tasks: utils.yml
