---
- name: Ensure packages for php development are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - php
    - php-gd
    - php-pgsql
    - xdebug
    - phpstorm
    - phpstorm-jre
    - composer
    - symfony-cli

- name: Ensure php.ini is copied
  copy:
    src: "files/php/php.ini"
    dest: "/etc/php/php.ini"
    owner: "diffy"
    group: "diffy"
    mode: '0644'
