---
- name: Ensure packages for php development are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
    - php
    - php-gd
    - php-pgsql
    - php-intl
    - xdebug
    - phpstorm
    - phpstorm-jre
    - composer
    - symfony-cli

- name: Ensure php.ini is copied
  copy:
    src: "files/php/php.ini"
    dest: "/etc/php/php.ini"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'
