---
- name: Ensure arandr instaled
  pacman:
    name:
      - arandr

- name: Ensure arandr config directory exists
  file:
    path: "/home/{{ system_user_name }}/.screenlayout"
    state: directory

- name: Ensure configs are in place
  ansible.builtin.copy:
    src: "files/.screenlayout/"
    dest: "/home/{{ system_user_name }}/.screenlayout/"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0744'
