---
- name: Install core packages from aur
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - flameshot

- name: Ensure flameshot config directory exists
  file:
    path: "/home/{{ system_user_name }}/.config/flameshot"
    state: directory

- name: Copy flameshot config
  template:
    src: files/utils/flameshot.ini.j2
    dest: "/home/{{ system_user_name }}/.config/flameshot.ini"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    mode: '0644'
