# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

[hostname]
ssh_only = false
format =  "on [$hostname](bold #88C0D0) [➜](bold #88C0D0) "
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true